export const TABLE_FIELDS = [
  {
      key: "",
      label: "#",
  },
  {
      key: "name",
      label: "Employee",
  },
  {
      key: "department",
      label: "Department",
  },
  {
      key: "attendance",
      label: "Attendance",
  },
  {
      key: "satisfaction",
      label: "Satisfaction",
  },
  {
      key: "performance",
      label: "Performance",
  },
]
export const TABLE_SECTIONS = [
  {
      type: "FILE",
      name: "Charles-Augustin de Coulomb",
      desc:"Director of Global Communication and Innovation",
      department:"Marketing",
      attendance:"98%",
      satisfaction:"98%",
      bgColor:"variant_green",
      performance:"5",
      preview: "https://loremflickr.com/640/360",
      extension: "png",
      __v: 0,
      active: false,
  },
  {
      type: "FILE",
      name: "Michael Faraday",
      desc:"Database Administrator",
      attendance:"98%",
      department:"IT",
      satisfaction:"98%",
      performance:"5",
      bgColor:"variant_green",
      extension: "png",
      preview: "https://loremflickr.com/640/360",
      __v: 0,
      active: false,
  },
  {
      type: "FILE",
      name: "Marie Sklodowask-Curie",
      desc:"UI/UX Designer",
      department:"Product Design",
      attendance:"38%",
      satisfaction:"98%",
      bgColor:"variant_yellow",
      performance:"5",
      extension: "png",
      preview: "https://loremflickr.com/640/360",
      __v: 0,
      active: false,
  },
  {
      type: "FILE",
      name: "John Dalton",
      desc:"Business Optimization Manager",
      department:"Opreations",
      attendance:"28%",
      satisfaction:"98%",
      bgColor:"variant_light_pink",
      performance:"5",
      extension: "png",
      preview: "https://loremflickr.com/640/360",
      __v: 0,
      active: false,
  },
  {
      type: "FILE",
      name: "Georg Simon Ohm",
      desc:"Marketing Manager",
      department:"Marketing",
      attendance:"18%",
      satisfaction:"98%",
      bgColor:"variant_gray",
      performance:"5",
      extension: "png",
      preview: "https://loremflickr.com/640/360",
      __v: 0,
      active: false,
  }
]