export const TABLE_FIELDS = [
  {
    key: "",
    label: "#",
  },
  {
    key: "name",
    label: "Employee",
  },
  {
    key: "department",
    label: "Department",
  },
  {
    key: "attendance",
    label: "Attendance",
  },
  {
    key: "satisfaction",
    label: "Satisfaction",
  },
  {
    key: "performance",
    label: "Performance",
  },
];
export const TABLE_SECTIONS = [
  {
    id: "1",
    name: "Charles-Augustin de Coulomb",
    color: "#2ba026",
    desc: "Director of Global Communication and Innovation",
    department: "Marketing",
    attendance: "98",
    satisfaction: "98",
    performance: 4.3,
    preview: "https://loremflickr.com/640/360",
    extension: "png",
    __v: 0,
    active: false,
  },
  {
    id: "2",
    name: "Michael Faraday",
    desc: "Database Administrator",
    attendance: "98",
    department: "IT",
    satisfaction: "48",
    performance: 3,
    extension: "png",
    preview: "https://loremflickr.com/640/360",
    __v: 0,
    active: false,
  },
  {
    id: "3",
    name: "Marie Sklodowask-Curie",
    desc: "UI/UX Designer",
    department: "Product Design",
    attendance: "38",
    satisfaction: "38",
    performance: 4.5,
    extension: "png",
    preview: "https://loremflickr.com/640/360",
    __v: 0,
    active: false,
  },
  {
    id: "4",
    name: "John Dalton",
    desc: "Business Optimization Manager",
    department: "Opreations",
    attendance: "28",
    satisfaction: "88",
    performance: 2.5,
    extension: "png",
    preview: "https://loremflickr.com/640/360",
    __v: 0,
    active: false,
  },
  {
    id: "5",
    name: "Georg Simon Ohm",
    desc: "Marketing Manager",
    department: "Marketing",
    attendance: "",
    satisfaction: "",
    performance: 1,
    extension: "png",
    preview: "https://loremflickr.com/640/360",
    __v: 0,
    active: false,
  },
];
export const USER_DETAILS = [
  {
    id: "1",
    name: "Charles-Augustin de Coulomb",
    midname: "Middle Name",
    lastname: "Vervelsky",
    email: "name@organization.com",
    mobile: "+1 514 555 8877",
    age: 36,
    birthday: "2021-09-22",
    time: "11:56",
    desc: "Director of Global Communication and Innovation",
    department: "Marketing",
    attendance: "98",
    satisfaction: "98",
    performance: 4.3,
    preview: "",
    extension: "png",
    gender: "Select Gender",
    genderOptions: [
      { label: "Please choose one", value: null },
      { label: "Male", value: "male" },
      { label: "Female", value: "female" },
    ],
    hireDate:"2021-01-14",
    socialInsuranceNumber:"3444 5444 6777",
    employeeNumber:"7565",
    employeeStatus:"Select Status",
    esstatusOptions: [
      { label: "Please choose one", value: null },
      { label: "Dummy Value", value: "value" },
      { label: "Dummy Value", value: "value" },
    ],
    department:"Select Department",
    departmentOptions: [
      { label: "Please choose one", value: null },
      { label: "IT", value: "value" },
      { label: "HR", value: "value" },
    ],
    team:"Select Team",
    teamOptions: [
      { label: "Please choose one", value: null },
      { label: "IT", value: "value" },
      { label: "HR", value: "value" },
    ],
    title:"Select Title",
    titleOptions: [
      { label: "Please choose one", value: null },
      { label: "IT", value: "value" },
      { label: "HR", value: "value" },
    ],
    reportsTo:"Select Reporting",
    reportsToOptions: [
      { label: "Please choose one", value: null },
      { label: "Bruno", value: "Bruno" },
      { label: "Kelvin", value: "kelvin" },
    ],
    
    __v: 0,
    active: false,
  },
  {
    id: "2",
    name: "Michael",
    lastname:"Faraday",
    desc: "Database Administrator",
    attendance: "98",
    department: "IT",
    satisfaction: "48",
    lastname: "Vervelsky",
    email: "name@organization.com",
    mobile: "+1 514 555 8877",
    age: 36,
    birthday: "2021-09-22",
    performance: 3,
    extension: "png",
    preview: "http://localhost:3000/_nuxt/_/bib-shared/img/black-logo.png",
    gender: "Male",
    genderOptions: [
      { label: "Please choose one", value: null },
      { label: "Male", value: "male" },
      { label: "Female", value: "female" },
    ],
    hireDate:"2021-01-14",
    socialInsuranceNumber:"3444 5444 6777",
    employeeNumber:"7565",
    employeeStatus:"Select Status",
    esstatusOptions: [
      { label: "Please choose one", value: null },
      { label: "Dummy Value", value: "value" },
      { label: "Dummy Value", value: "value" },
    ],
    department:"Select Department",
    departmentOptions: [
      { label: "Please choose one", value: null },
      { label: "IT", value: "value" },
      { label: "HR", value: "value" },
    ],
    team:"Select Team",
    teamOptions: [
      { label: "Please choose one", value: null },
      { label: "IT", value: "value" },
      { label: "HR", value: "value" },
    ],
    title:"Select Title",
    titleOptions: [
      { label: "Please choose one", value: null },
      { label: "IT", value: "value" },
      { label: "HR", value: "value" },
    ],
    reportsTo:"Select Reporting",
    reportsToOptions: [
      { label: "Please choose one", value: null },
      { label: "Bruno", value: "Bruno" },
      { label: "Kelvin", value: "kelvin" },
    ],
    __v: 0,
    active: false,
  },
  {
    id: "3",
    name: "Marie Sklodowask-Curie",
    desc: "UI/UX Designer",
    department: "Product Design",
    attendance: "38",
    satisfaction: "38",
    performance: 4.5,
    extension: "png",
    preview: "",
    __v: 0,
    active: false,
  },
  {
    id: "4",
    name: "John Dalton",
    desc: "Business Optimization Manager",
    department: "Opreations",
    attendance: "28",
    satisfaction: "88",
    performance: 2.5,
    extension: "png",
    preview: "https://loremflickr.com/640/360",
    __v: 0,
    active: false,
  },
  {
    id: "5",
    name: "Georg Simon Ohm",
    desc: "Marketing Manager",
    department: "Marketing",
    attendance: "",
    satisfaction: "",
    performance: 1,
    extension: "png",
    preview: "https://loremflickr.com/640/360",
    __v: 0,
    active: false,
  },
];
export const PERSONAL_INFO_TAB = [
  {
    title: "Personal Information",
    value: "personal-information",
  },
  {
    title: "Address",
    value: "address",
  },
  {
    title: "Contacts",
    value: "contacts",
  },
];
export const EMPLOYEE_INFO_TAB = [
  {
    title: "Employment Information",
    value: "employment-information",
  },
  {
    title: "Compensation",
    value: "compensation",
  },
  {
    title: "Benefits",
    value: "benefits",
  },
  {
    title: "Time-off",
    value: "time-off",
  },
  {
    title: "Attendance",
    value: "attendance",
  },
  {
    title: "Files",
    value: "files",
  },
]