export const DASHBOARD_DATA = [
  {
    id: "63b64e0b9a8c618c76610466",
    businessId: "O3GWpmbk5ezJn4KR",
    userId: "gELYqaQWQG9dnjk2",
    role: "USER",
    firstName: "Rajeev",
    middleName: "Sharma", 
    lastName: "Sharma",
    jobTitle:"Technical",
    email: "rajeev.sharma@qsstechnosoft.com",
    status: "Online",
    in:"08:00",
    out:"00:00",
    breaks:"00:00",
    totalHours:"03:00",
    photo:
      "https://dev-bib-account-storagebucket.s3.amazonaws.com/user_avatar_1674473092167.jpg",
    useOrganizationSettings: true,
  },
  {
    id: "63b64e0b9a8c618c76610466",
    businessId: "O3GWpmbk5ezJn4KR",
    userId: "gELYqaQWQG9dnjk2",
    role: "USER",
    firstName: "Rajeev",
    middleName: "Sharma", 
    lastName: "Sharma",
    jobTitle:"Technical",
    email: "rajeev.sharma@qsstechnosoft.com",
    status: "Break",
    in:"00:00",
    out:"00:00",
    breaks:"00:00",
    totalHours:"05:00",
    photo:
      "https://dev-bib-account-storagebucket.s3.amazonaws.com/user_avatar_1674473092167.jpg",
    useOrganizationSettings: true,
  },
  {
    id: "63b64e0b9a8c618c76610466",
    businessId: "O3GWpmbk5ezJn4KR",
    userId: "gELYqaQWQG9dnjk2",
    role: "USER",
    firstName: "Rajeev",
    middleName: "Sharma", 
    lastName: "Sharma",
    jobTitle:"Technical",
    email: "rajeev.sharma@qsstechnosoft.com",
    status: "Break",
    in:"00:00",
    out:"00:00",
    breaks:"00:00",
    totalHours:"03:00",
    photo:
      "https://dev-bib-account-storagebucket.s3.amazonaws.com/user_avatar_1674473092167.jpg",
    useOrganizationSettings: true,
  },
  {
    id: "63b64e0b9a8c618c76610466",
    businessId: "O3GWpmbk5ezJn4KR",
    userId: "gELYqaQWQG9dnjk2",
    role: "USER",
    firstName: "Rajeev",
    middleName: "Sharma", 
    lastName: "Sharma",
    jobTitle:"Technical",
    email: "rajeev.sharma@qsstechnosoft.com",
    status: "Absent",
    in:"00:00",
    out:"09:30",
    breaks:"00:60",
    totalHours:"08:00",
    photo:
      "https://dev-bib-account-storagebucket.s3.amazonaws.com/user_avatar_1674473092167.jpg",
    useOrganizationSettings: true,
  },
];
export const INBOX_DATA = [
  {
    id: "63b64e0b9a8c618c76610466",
    businessId: "O3GWpmbk5ezJn4KR",
    userId: "gELYqaQWQG9dnjk2",
    role: "USER",
    firstName: "Rajeev",
    middleName: "Sharma", 
    lastName: "Sharma",
    jobTitle:"Technical",
    email: "rajeev.sharma@qsstechnosoft.com",
    type: "Absence",
    subject:"Subject",
    received:"00:00:00 - 00-00-0000",
  },
  {
    id: "63b64e0b9a8c618c76610466",
    businessId: "O3GWpmbk5ezJn4KR",
    userId: "gELYqaQWQG9dnjk2",
    role: "USER",
    firstName: "Rajeev",
    middleName: "Sharma", 
    lastName: "Sharma",
    jobTitle:"Technical",
    email: "rajeev.sharma@qsstechnosoft.com",
    type: "Absence",
    subject:"Subject",
    received:"00:00:00 - 00-00-0000",
  },
  {
    id: "63b64e0b9a8c618c76610466",
    businessId: "O3GWpmbk5ezJn4KR",
    userId: "gELYqaQWQG9dnjk2",
    role: "USER",
    firstName: "Rajeev",
    middleName: "Sharma", 
    lastName: "Sharma",
    jobTitle:"Technical",
    email: "rajeev.sharma@qsstechnosoft.com",
    type: "Absence",
    subject:"Subject",
    received:"00:00:00 - 00-00-0000",
  },
  {
    id: "63b64e0b9a8c618c76610466",
    businessId: "O3GWpmbk5ezJn4KR",
    userId: "gELYqaQWQG9dnjk2",
    role: "USER",
    firstName: "Rajeev",
    middleName: "Sharma", 
    lastName: "Sharma",
    jobTitle:"Technical",
    email: "rajeev.sharma@qsstechnosoft.com",
    type: "Absence",
    subject:"Subject",
    received:"00:00:00 - 00-00-0000",
  },
];
export const INFO_CARD_DATA = [
  {
    title: "Absent Today",
    numberData:"2",
  },
  {
    title: "Absence notifications",
    numberData:"1",
  },
  {
    title: "Present",
    numberData:"42",
  },
  {
    title: "On vacation",
    numberData:"2",
  },
  {
    title: "On leave",
    numberData:"2",
  },
  {
    title: "Past due timesheets",
    numberData:"2",
  },
  {
    title: "Pending timesheets",
    numberData:"2",
  },
  {
    title: "Attendance",
    numberData:"95%",
  },
];
export const INBOX_CARD_DATA = [
  {
    title: "New messages",
    numberData:"2",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    title: "Absence notifications",
    numberData:"1",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    title: "Leave requests",
    numberData:"3",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    title: "Vacation requests",
    numberData:"2",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
]
export const INBOX_CARD_NEW_MESSAGE_DATA = [
  {
    title: "Allowance",
    numberData:"21",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    title: "Used",
    numberData:"10",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    title: "Available",
    numberData:"11",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
]
export const LEAVE_CARD_DATA = [
  {
    title: "Vacations",
    numberData:"Available",
    totalDays:"23",
    daysDesc:"Days",
    allowance:"31",
    used:"4",
  },
  {
    title: "Medical/Sick",
    numberData:"Available",
    totalDays:"04",
    daysDesc:"Days",
    allowance:"31",
    used:"4",
  },
  {
    title: "Other",
    numberData:"Available",
    totalDays:"00",
    daysDesc:"Days",
    allowance:"31",
    used:"4",
  },
]