version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo $NPM_AUTH_TOKEN >> .npmrc
      - echo copying environment files
      - aws s3 cp ${STAGE_ENV_FILE_PATH} app.env
      - aws s3 cp ${GLOBAL_ENV_FILE_PATH} global.env
      - cat app.env global.env >> .env      
  build:
    commands:
      - echo node version
      - node -v
      - echo installing dependencies
      - yarn install
      - echo Building the Front End distro...
      - yarn run generate --fail-on-error
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: 'dist'

  files:
    - '**/*'
