version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo $NPM_AUTH_TOKEN >> .npmrc
      - echo copying environment files
      - aws s3 cp ${STAGE_ENV_FILE_PATH} app.env
      - aws s3 cp ${GLOBAL_ENV_FILE_PATH} global.env
      - cat app.env global.env >> .env      
      - ls -la
  build:
    commands:
      - echo node version
      - node -v
      - echo $PROJECT_NAME
      - echo $BRANCH_NAME
      - |
        if [ "$BRANCH_NAME" = "master" ] || [ "$BRANCH_NAME" = "main" ]; then
          echo "On dev branch, performing backup..."
          aws s3 cp /codebuild/output s3://biztree-git-backup-bucket/$PROJECT_NAME/$BRANCH_NAME/$(date +%Y-%m-%d_%H-%M-%S)/ --recursive
          echo "s3 backup complete"
        else
          echo "Not on dev branch, skipping backup."
        fi
      - echo installing dependencies
      - npm ci
      - echo Building the Front End distro...
      - npm run generate --fail-on-error
  post_build:
    commands:
      - echo Build completed on `date`
      - >
        echo '[' > dist/_nuxt_contents.json &&
        find dist/_nuxt -type f | awk -F/ '{print "\"" $NF "\""}' | paste -sd, - >> dist/_nuxt_contents.json &&
        echo ']' >> dist/_nuxt_contents.json
      - cat dist/_nuxt_contents.json
artifacts:
  base-directory: 'dist'

  files:
    - '**/*'
