version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Installign BIB Shared components library
      - echo Installign dependencies...
      - cp -r ../../github.com/Biztree/bib-shared .
      - echo copying environment files
      - aws s3 cp ${STAGE_ENV_FILE_PATH} app.env
      - aws s3 cp ${GLOBAL_ENV_FILE_PATH} global.env
      - cat app.env global.env >> .env      
      - echo installing dependencies
      - yarn install
      - echo Building the Front End distro...
      - yarn run generate
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: 'dist'

  files:
    - '**/*'
